-- Generated by tools/sync-items-data.mjs. Keeps inventory, effects and API wrappers intact.
begin;
-- ITEM_CONFIG_BEGIN
insert into public.wakppu_item_defs values ('common_honey_small','common',300,'honey',125,0,'break'),
('common_crack_piece','common',0,'add',2,30,'hit'),
('common_wax_polish','common',0,'reward',125,1,'break'),
('common_mini_hammer','common',0,'add',3,20,'hit'),
('common_lucky_wax','common',0,'reward',150,10,'break'),
('common_candle','common',300,'add',1,0,'hit'),
('common_wax_thread','common',0,'add',2,20,'hit'),
('common_wax_feather','common',300,'animation',125,0,'break'),
('common_micro_elixir','common',0,'reward',125,3,'break'),
('common_wax_coin','common',0,'reward',120,10,'break'),
('rare_honey','rare',600,'honey',150,0,'break'),
('rare_crack_booster','rare',120,'damage',150,0,'break'),
('rare_wax_coating','rare',0,'reward',200,5,'break'),
('rare_iron_hammer','rare',0,'add',10,50,'hit'),
('rare_lucky_crystal','rare',600,'reward',150,0,'break'),
('rare_concentrated_honey','rare',600,'honey',175,0,'break'),
('rare_strong_crack_booster','rare',180,'damage',175,0,'break'),
('rare_advanced_coating','rare',0,'reward',175,10,'break'),
('rare_reinforced_hammer','rare',0,'add',15,50,'hit'),
('rare_amplifying_crystal','rare',600,'reward',175,0,'break'),
('hero_golden_honey','hero',900,'honey',200,0,'break'),
('hero_explosion_crystal','hero',300,'damage',200,0,'break'),
('hero_time_wax','hero',180,'difficulty',50,0,'break'),
('hero_explosive_wax','hero',300,'damage',250,0,'break'),
('hero_gem_honey','hero',900,'honey',250,0,'break'),
('hero_haste_wax','hero',300,'damage',200,0,'break'),
('hero_destruction_crystal','hero',0,'reward',300,10,'break'),
('legendary_destruction_core','legendary',600,'damage',300,0,'break'),
('legendary_golden_coating','legendary',0,'reward',400,20,'break'),
('transcendent_wax_heart','transcendent',1800,'heart',300,0,'break') on conflict(item_id) do update set rank=excluded.rank,seconds=excluded.seconds,channel=excluded.channel,value=excluded.value,charges=excluded.charges,unit=excluded.unit;
insert into public.wakppu_item_ranks values ('common',0,7000),('rare',1,2200),('hero',2,600),('legendary',3,190),('transcendent',4,10) on conflict(rank) do update set position=excluded.position,weight=excluded.weight;
-- ITEM_CONFIG_END
commit;
