-- Generated by tools/sync-limited-sql.mjs; apply after item API and other existing wrappers.
begin;
create table if not exists public.wakppu_limited_settings(id boolean primary key default true check(id),starts_at timestamptz not null,ends_at timestamptz not null,check(ends_at>starts_at));
insert into public.wakppu_limited_settings values(true,'2026-10-23T15:00:00Z','2026-11-14T15:00:00Z') on conflict(id) do nothing;
create table if not exists public.wakppu_limited_players(user_id uuid primary key references public.players(user_id) on delete cascade,tokens bigint not null default 0 check(tokens>=0),owned jsonb not null default '{}',selected text,clicks bigint not null default 0);
create table if not exists public.wakppu_limited_requests(user_id uuid references public.players(user_id) on delete cascade,request_id uuid,action text not null,response jsonb not null,primary key(user_id,request_id));
update public.wakppu_limited_players set owned=jsonb_set(owned,array['halloween-pumpkin-2026','reward'],to_jsonb('1500000000'::text)) where owned ? 'halloween-pumpkin-2026';
alter table public.wakppu_limited_settings enable row level security;
alter table public.wakppu_limited_players enable row level security;
alter table public.wakppu_limited_requests enable row level security;
revoke all on public.wakppu_limited_settings,public.wakppu_limited_players,public.wakppu_limited_requests from public,anon,authenticated;
do $migration$ begin if to_regprocedure('public.wakppu_api_before_limited(jsonb)') is null then alter function public.wakppu_api(jsonb) rename to wakppu_api_before_limited;end if;end $migration$;
revoke all on function public.wakppu_api_before_limited(jsonb) from public,anon,authenticated;
create or replace function public.wakppu_api(b jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $api$
declare a text:=b->>'action';u uuid:=auth.uid();instant timestamptz:=clock_timestamp();ms bigint:=floor(extract(epoch from instant)*1000);
 settings public.wakppu_limited_settings%rowtype;l public.wakppu_limited_players%rowtype;s public.game_states%rowtype;inv public.wakppu_items%rowtype;d public.wakppu_item_defs%rowtype;
 active boolean;result jsonb;previous jsonb;cached jsonb;cached_action text;info jsonb;earned numeric:=0;base_reward numeric;total_hits bigint;hits bigint;damage bigint;
 honey numeric:=1;bonus numeric:=1;damage_mult numeric:=1;addition numeric:=0;difficulty numeric:=1;multiplier numeric;winners jsonb:='{}';it record;stat jsonb;event jsonb;dropped boolean:=false;
begin
 if a not in ('limited','limited_buy','limited_select','limited_hit','item_hit') then return public.wakppu_api_before_limited(b);end if;
 previous:=public.wakppu_api_before_limited(jsonb_build_object('action','bootstrap'));
 select * into s from public.game_states where user_id=u for update;
 insert into public.wakppu_limited_players(user_id) values(u) on conflict do nothing;
 select * into l from public.wakppu_limited_players where user_id=u for update;
 select * into settings from public.wakppu_limited_settings where id=true;
 active:=instant>=settings.starts_at and instant<settings.ends_at;
 if a<>'limited' then
  if coalesce(b->>'request_id','') !~ '^[a-f0-9-]{36}$' then raise exception '잘못된 요청 ID';end if;
  select response,action into cached,cached_action from public.wakppu_limited_requests where user_id=u and request_id=(b->>'request_id')::uuid;
  if found then if cached_action<>a then raise exception '요청 ID 충돌';end if;return cached;end if;
  if coalesce((b->>'item_revision')::bigint,-1)<>s.item_revision then raise sqlstate 'PT409' using message='상태를 다시 불러옵니다.';end if;
 end if;
 if a='item_hit' then
  result:=public.wakppu_api_before_limited(b);
  if active and b->>'event_id' is null and (result->>'reward')::numeric>0 and (('x'||substr(replace(gen_random_uuid()::text,'-',''),1,8))::bit(32)::bigint)/4294967296.0<0.1 then l.tokens:=l.tokens+1;dropped:=true;end if;
 elsif a='limited_buy' then
  if not active then raise sqlstate 'PT409' using message='할로윈 이벤트 기간이 아닙니다.';end if;
  if l.owned ? 'halloween-pumpkin-2026' then raise sqlstate 'PT409' using message='이미 보유한 한정 볼입니다.';end if;
  if l.tokens<100 then raise exception '할로윈 사탕이 부족합니다.';end if;
  base_reward:=1500000000;
  l.tokens:=l.tokens-100;l.owned:=jsonb_set(l.owned,array['halloween-pumpkin-2026'],jsonb_build_object('reward',base_reward::text));
 elsif a='limited_select' then
  if not b ? 'ball_id' or (b->>'ball_id' is not null and not l.owned ? (b->>'ball_id')) then raise exception '보유한 한정 볼이 아닙니다.';end if;
  l.selected:=b->>'ball_id';l.clicks:=0;
 elsif a='limited_hit' then
  if l.selected is null or not l.owned ? l.selected then raise exception '한정 볼을 선택해주세요.';end if;
  insert into public.wakppu_items(user_id) values(u) on conflict do nothing;
  select * into inv from public.wakppu_items where user_id=u for update;
  honey:=case when s.honey_expires_at>instant then 2 else 1 end;bonus:=case when s.coating_expires_at>instant then 3 else 1 end;
  for it in select def.*,e.value as effect from jsonb_each(inv.effects) e join public.wakppu_item_defs def on def.item_id=e.key order by def.item_id loop
   if not (case when it.seconds>0 then coalesce((it.effect->>'expires_at')::bigint,0)>ms else coalesce((it.effect->>'remaining')::bigint,0)>0 end) then continue; end if;
   if it.channel='honey' and it.value/100.0>honey then honey:=it.value/100.0;winners:=jsonb_set(winners,array['honey'],to_jsonb(it.item_id)); end if;
   if it.channel in ('reward','heart') and it.value/100.0>bonus then bonus:=it.value/100.0;winners:=jsonb_set(winners,array['reward'],to_jsonb(it.item_id)); end if;
   multiplier:=case when it.channel='heart' then 2 else it.value/100.0 end;
   if it.channel in ('damage','heart') and multiplier>damage_mult then damage_mult:=multiplier;winners:=jsonb_set(winners,array['damage'],to_jsonb(it.item_id)); end if;
   if it.channel='add' and it.value>addition then addition:=it.value;winners:=jsonb_set(winners,array['add'],to_jsonb(it.item_id)); end if;
   if it.channel='difficulty' and multiplier<difficulty then difficulty:=multiplier;winners:=jsonb_set(winners,array['difficulty'],to_jsonb(it.item_id)); end if;
  end loop;

  total_hits:=greatest(1,ceil(100*(case when s.coating_expires_at>instant then 2 else 1 end)*difficulty));
  damage:=greatest(1,floor((public.wakppu_hammer_damage(s.hammer_owned,s.hammer_level)+addition)*damage_mult));hits:=least(total_hits,l.clicks+damage);
  if hits=total_hits then
   stat:=public.wakppu_api_before_limited(jsonb_build_object('action','status'));event:=stat->'gold_event';multiplier:=1;
   if event is not null and event<>'null'::jsonb and instant>=(event->>'starts_at')::timestamptz and instant<(event->>'ends_at')::timestamptz then multiplier:=(event->>'multiplier')::numeric;end if;
   earned:=floor(1500000000::numeric*power(2::numeric,s.rebirths)*honey*bonus*multiplier);s.gold:=s.gold+earned;
  end if;
  for it in select distinct value #>> '{}' as id from jsonb_each(winners) loop
   select * into d from public.wakppu_item_defs where item_id=it.id;
   if d.seconds=0 and (d.unit='hit' or hits=total_hits) then inv.effects:=jsonb_set(inv.effects,array[d.item_id,'remaining'],to_jsonb(greatest(0,(inv.effects->d.item_id->>'remaining')::bigint-1)));end if;
  end loop;

  update public.wakppu_items set effects=inv.effects where user_id=u;l.clicks:=case when hits=total_hits then 0 else hits end;
 end if;
 if a in ('limited_buy','limited_select','limited_hit') then update public.game_states set item_revision=item_revision+1,gold=s.gold where user_id=u;end if;
 if a not in ('limited','item_hit') then result:=public.wakppu_api_before_limited(jsonb_build_object('action','items'));end if;
 update public.wakppu_limited_players set tokens=l.tokens,owned=l.owned,selected=l.selected,clicks=l.clicks where user_id=u;
 info:=jsonb_build_object('season',jsonb_build_object('id','halloween-2026','name','🎃 할로윈 2026','starts_at',settings.starts_at,'ends_at',settings.ends_at,'active',active,'dropChance',0.1,'cost',100),'tokens',l.tokens,'owned',l.owned,'selected',l.selected,'clicks',l.clicks);
 if a='limited' then return info;end if;
 result:=result||jsonb_build_object('limited',info,'candy_drop',dropped);
 if a='limited_hit' then result:=result||jsonb_build_object('clicks',hits,'required_clicks',total_hits,'reward',earned::text);end if;
 insert into public.wakppu_limited_requests values(u,(b->>'request_id')::uuid,a,result);return result;
end $api$;
revoke all on function public.wakppu_api(jsonb) from public,anon;
grant execute on function public.wakppu_api(jsonb) to authenticated;
commit;
