-- Generated by tools/sync-items-data.mjs. Keeps inventory, effects and API wrappers intact.
begin;
-- ITEM_CONFIG_BEGIN
insert into public.wakppu_item_defs values ('common_honey_small','common',300,'reward',125,0,'break'),
('common_crack_piece','common',0,'respawn',110,30,'break'),
('common_wax_polish','common',0,'reward',125,1,'break'),
('common_mini_hammer','common',0,'respawn',115,20,'break'),
('common_lucky_wax','common',0,'reward',150,10,'break'),
('common_candle','common',300,'respawn',105,0,'break'),
('common_wax_thread','common',0,'respawn',110,20,'break'),
('common_wax_feather','common',300,'animation',125,0,'break'),
('common_micro_elixir','common',0,'reward',125,3,'break'),
('common_wax_coin','common',0,'reward',120,10,'break'),
('rare_honey','rare',600,'reward',150,0,'break'),
('rare_crack_booster','rare',120,'respawn',150,0,'break'),
('rare_wax_coating','rare',0,'reward',200,5,'break'),
('rare_iron_hammer','rare',0,'respawn',150,50,'break'),
('rare_lucky_crystal','rare',600,'reward',150,0,'break'),
('rare_concentrated_honey','rare',600,'reward',175,0,'break'),
('rare_strong_crack_booster','rare',180,'respawn',175,0,'break'),
('rare_advanced_coating','rare',0,'reward',175,10,'break'),
('rare_reinforced_hammer','rare',0,'respawn',175,50,'break'),
('rare_amplifying_crystal','rare',600,'reward',175,0,'break'),
('hero_golden_honey','hero',900,'reward',200,0,'break'),
('hero_explosion_crystal','hero',300,'respawn',200,0,'break'),
('hero_time_wax','hero',180,'respawn',200,0,'break'),
('hero_explosive_wax','hero',300,'respawn',250,0,'break'),
('hero_gem_honey','hero',900,'reward',250,0,'break'),
('hero_haste_wax','hero',300,'respawn',200,0,'break'),
('hero_destruction_crystal','hero',0,'reward',300,10,'break'),
('legendary_destruction_core','legendary',600,'respawn',300,0,'break'),
('legendary_golden_coating','legendary',0,'reward',400,20,'break'),
('transcendent_wax_heart','transcendent',1800,'heart',300,0,'break') on conflict(item_id) do update set rank=excluded.rank,seconds=excluded.seconds,channel=excluded.channel,value=excluded.value,charges=excluded.charges,unit=excluded.unit;
insert into public.wakppu_item_ranks values ('common',0,7000),('rare',1,2200),('hero',2,600),('legendary',3,190),('transcendent',4,10) on conflict(rank) do update set position=excluded.position,weight=excluded.weight;
-- ITEM_CONFIG_END
-- Shared server winner selection, independent from shop multipliers.
create or replace function public.wakppu_item_winners(effects jsonb,ms bigint)
returns jsonb language plpgsql set search_path=public,pg_temp as $fn$
declare it record; result jsonb:='{}'; channels jsonb; pair record;
begin
 for it in select def.*,e.value as effect from jsonb_each(effects) e
  join public.wakppu_item_defs def on def.item_id=e.key order by def.item_id loop
  if not (case when it.seconds>0 then coalesce((it.effect->>'expires_at')::bigint,0)>ms
   else coalesce((it.effect->>'remaining')::bigint,0)>0 end) then continue;end if;
  channels:=case when it.channel='heart' then '{"reward":300,"animation":200,"respawn":300}'::jsonb
   when it.item_id='hero_haste_wax' then '{"respawn":200,"animation":150}'::jsonb
   else jsonb_build_object(it.channel,it.value) end;
  for pair in select key,value from jsonb_each_text(channels) loop
   if pair.value::numeric>coalesce((result->pair.key->>'value')::numeric,100) then
    result:=jsonb_set(result,array[pair.key],jsonb_build_object('value',pair.value::numeric,'id',it.item_id));
   end if;
  end loop;
 end loop;
 return result;
end $fn$;
revoke all on function public.wakppu_item_winners(jsonb,bigint) from public,anon,authenticated;
-- Patch only the effect calculation inside existing normal/event/limited APIs.
-- Do not replace the wrapper stack or touch player inventory/effects.
do $migration$
declare f record; source text; updated text; count_changed integer:=0;
begin
 for f in select p.oid from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.prokind='f' and p.prosrc like '%jsonb_each(inv.effects)%' loop
  source:=pg_get_functiondef(f.oid);
  updated:=regexp_replace(source,'honey:=case.*?end loop;',
   $replacement$honey:=case when s.honey_expires_at>instant then 2 else 1 end;
  bonus:=case when s.coating_expires_at>instant then 3 else 1 end;
  winners:=public.wakppu_item_winners(inv.effects,ms);
  bonus:=bonus*coalesce((winners->'reward'->>'value')::numeric/100,1);
  addition:=0;damage_mult:=1;difficulty:=1;$replacement$,'s');
  if updated=source then raise exception 'Unexpected item effect loop: %',f.oid::regprocedure;end if;
  updated:=replace(updated,'select distinct value #>> ''{}'' as id from jsonb_each(winners)',
    'select distinct value->>''id'' as id from jsonb_each(winners) where value ? ''id''');
  if position('value->>''id'' as id' in updated)=0 then raise exception 'Unexpected item consumption: %',f.oid::regprocedure;end if;
  execute updated;count_changed:=count_changed+1;
 end loop;
 if count_changed=0 and not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace
   where n.nspname='public' and p.prosrc like '%winners:=public.wakppu_item_winners(inv.effects,ms)%') then
  raise exception 'No item API found';
 end if;
end $migration$;
commit;
